version: '3.8'

services:
  smm-backend:
    image: smm-backend:0.0.1
    build:
      context: .
    container_name: smm-backend
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/smm_backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      - smm-backend

  postgres-db:
    image: postgres:15.2
    container_name: postgres-db
    environment:
      - POSTGRES_DB=smm_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - smm-backend
    ports:
      - 5432:5432

networks:
  smm-backend:
    name: smm-backend
    driver: bridge
