version: '0.0.1'

services:
  smm-backend:
    image: smm-backend:0.0.1
    build:
      context: .
    container_name: smm-backend
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - smm-backend

  postgresdb:
    image: arm64v8/postgres:15.2-alpine
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - smm-backend

networks:
  smm-backend:
    name: smm-backend
    driver: bridge

