version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/keycloak/data/import
    command:
      - start-dev --import-realm
